FROM node:12.13-alpine

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
COPY webpack.config.js ./
COPY webpack.prod.config.js ./

RUN npm install -g yarn

RUN yarn install

COPY . .

CMD ["yarn", "dev"]