FROM node:12.16.3

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
COPY webpack.config.js ./
COPY webpack.prod.config.js ./

# RUN npm install -g yarn

# ENV NODE_ENV development

# いらないかも
RUN npm link webpack

# RUN yarn install
RUN npm install

COPY . .

# CMD ["yarn", "dev"]
CMD ["npm", "run", "dev"]