apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yoshijifujiwara/tulip-backend
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_HOST
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: MYSQL_DATABASE
            - name: BACKEND_INNER_PORT
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: BACKEND_INNER_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: JWT_SECRET
            - name: PRODUCTION_MODE
              value: true
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 3000
      targetPort: 3000
