apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yoshijifujiwara/tulip-frontend
          env:
            - name: AXIOS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: AXIOS_BASE_URL
            - name: VR_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: VR_BASE_URL
            - name: CLOUDINARY_UPLOAD_PRESET
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: CLOUDINARY_UPLOAD_PRESET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: tulip-local-secrets
                  key: CLOUDINARY_CLOUD_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
