name: deploy-frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && docker build -t yoshijifujiwara/tulip-frontend --file ./Dockerfile.prod .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yoshijifujiwara/tulip-frontend
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tulip
      - run: kubectl delete secrets tulip-local-secrets
      - run: kubectl create secret generic tulip-local-secrets --from-env-file=.env.prod
      - run: kubectl rollout restart deployment client-depl
