name: test-frontend

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && npm install && npm run lint && npm run test
